version: "3.8"

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    ports:
      - "80:80"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db

  db:
    restart: always
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres